[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[profile.default.fuzz]
runs = 256

[profile.ci]
runs = 10000

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }

